// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvCfpfJ06aFtOqXfJPsarroBMSx8qsSbM',
    appId: '1:658501140287:web:bf94e397897e6122e75d8a',
    messagingSenderId: '658501140287',
    projectId: 'carrental-dadd7',
    authDomain: 'carrental-dadd7.firebaseapp.com',
    storageBucket: 'carrental-dadd7.appspot.com',
    measurementId: 'G-XLLT4MTST5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh32UmCr6lFSMeFG1tQqW_QcpxA3tkjX0',
    appId: '1:658501140287:android:645fab95ddc0e3bce75d8a',
    messagingSenderId: '658501140287',
    projectId: 'carrental-dadd7',
    storageBucket: 'carrental-dadd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlwk6iFfY0iuAyW-r-rxsoGcMWk3uNMcQ',
    appId: '1:658501140287:ios:3991fe4f5347d9e4e75d8a',
    messagingSenderId: '658501140287',
    projectId: 'carrental-dadd7',
    storageBucket: 'carrental-dadd7.appspot.com',
    iosBundleId: 'com.sobgog.carRental',
  );
}
